micronaut:
  server:
    port: 8703
  application:
    name: payee-service-micronaut
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/mnpayment
    username: restcrud
    password: restcrud
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

netty:
  default:
    allocator:
      max-order: 3
