micronaut:
  server:
    port: 8706
  application:
    name: payee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mnpayment
    username: restcrud
    password: restcrud
    driverClassName: org.postgresql.Driver
  jpa:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update


