micronaut:
  server:
    port: 8703
  application:
    name: payee-service-micronaut
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/rest-crud
    username: postgres
    password: restcrud
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

netty:
  default:
    allocator:
      max-order: 3
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
endpoints:
  health:
    enabled: true
    sensitive: false
